# Generated by Django 5.0.6 on 2024-05-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_identify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phonenumber',
            new_name='phoneNumber',
        ),
    ]
